# Site settings
title: "Owen Schebella"
# description: 
#   Hi, I'm Owen, a product designer at [Link Text](http://www.linkadress.com) working on conversational experiences and AI. Previously at Inference.

# author: Owen Schebella
# email: oschebell@gmail.com
# twitter_username: _HairForceOne
github_username: oschebell

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://owenschebella.com" # the base hostname & protocol for your site

# google_analytics_id: UA-1111111111-1
# disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

